
export const GET_PROFESSIONALS_START = 'GET_PROFESSIONALS_START'
export const GET_PROFESSIONALS_SUCCESS = 'GET_PROFESSIONALS_SUCCESS'
export const GET_PROFESSIONALS_ERROR = 'GET_PROFESSIONALS_ERROR'
